default: &default
  schemas_path: <%= "#{Rails.root}/spec/support/api/schemas/" %>
  schemas_host: 'http://localhost:3000'

development:
  <<: *default

test:
  <<: *default
  
production:
  <<: *default
  schemas_host: <%= ENV["SCHEMAS_HOST"] %>